= Book
:nofooter:

== Статистическое распределение Бейли

Имеем жир, содержащий насыщенные ($S$) и ненасыщенные ($U$) кислоты.

Сумма концентраций равна 100%:

$[S] + [U] = 1$

При статистическом распределении, опираясь на правила теории вероятности,
концентрации ТАГов типового состава выражаются соответствующими членама
разложения бинома:

$([S] + [U])^3 = [S]^3 + 3 * [S]^2 * [U] + 3 * [S] * [U]^2 + [U]^3 = 1$

Пусть $A, B, C$ - последовательность из трех *независимых* случайных величин,
имеющих одинаковое *распределение Бернулли* с параметром $p$ ($q = 1 - p$).
Тогда случайная величина $Y = A + B + C$ будет иметь биномиальное распределение
с параметрами $n$ и $p$.

$Y\sim \mathrm{Bin}(n, p)$

*Функция вероятности*:

$p_Y(k)\equiv \mathbb{P}(Y = k) = \binom{n}{k} p^k q^{n-k}, k = 0, \ldots, n$

Где *биномиальный коэффициент*:

$\binom{n}{k} = C_n^k = \frac{n!}{(n - k)!k!}$

Для $n = 3$ и $p = [S]$ ($q = [U] = 1 - [S]$).

$Y\sim \mathrm{Bin}(3, [S])$

$$\begin{cases}
  p_Y(0)\equiv \mathbb{P}(Y = 0) = \binom{3}{0}p^0q^3 = [U]^3 & [U_3]\\
  p_Y(1)\equiv \mathbb{P}(Y = 1) = \binom{3}{1}p^1q^2 = 3 * [S][U]^2 & [U_2S]\\
  p_Y(2)\equiv \mathbb{P}(Y = 2) = \binom{3}{2}p^2q^1 = 3 * [S]^2[U] & [US_2]\\
  p_Y(3)\equiv \mathbb{P}(Y = 3) = \binom{3}{3}p^3q^0 = [S]^3 & [S_3]
\end{cases}$$

Для $n = 2$ и $p = [S]$ ($q = [U] = 1 - [S]$).

$Y\sim \mathrm{Bin}(2, [S])$

$$\begin{cases}
  p_Y(0)\equiv \mathbb{P}(Y = 0) = \binom{2}{0}p^0q^2 = [U]^2 & [U_2]\\
  p_Y(1)\equiv \mathbb{P}(Y = 1) = \binom{2}{1}p^1q^1 = 2 * [S][U] & [SU]\\
  p_Y(2)\equiv \mathbb{P}(Y = 2) = \binom{2}{2}p^2q^0 = [S]^2 & [S_2]
\end{cases}$$

Для $n = 1$ и $p = [S]$ ($q = [U] = 1 - [S]$).

$Y\sim \mathrm{Bin}(1, [S])$

$$\begin{cases}
  p_Y(0)\equiv \mathbb{P}(Y = 0) = \binom{1}{0}p^0q^1 = [U] & [U]\\
  p_Y(1)\equiv \mathbb{P}(Y = 1) = \binom{1}{1}p^0q^1 = [S] & [S]
\end{cases}$$

Conversion factor:

$$\begin{cases}
  (f_{S_3})_C = 0\\
  (f_{S_2V})_C = 0\\
  (f_{SV_2})_C = 10^4 / [U]^2\\
  (f_{V_3})_C = 10^4 * (100 - 3 * [S]) / [U]^3
\end{cases}$$

Очевидно, что если семена данного растения не содержат других ТГ, кроме $SUU$ и $UUU$ (т.е. если $[S_3]_C = 0$ и $[S_2U]_C = 0$) , то молярная концентрация $SU_2$ должна быть равна трехкратному содержанию насыщенных ФА в сумме ФА ($[SU_2]_C = [SUU] + [UUS] + [USU] = 3[S]$), а концентрация $U$ - разнице между 100 моль % и $3 * [S]$ моль %, т.е. $[U_3]_C = 100 - 3[S]$

Если не содержится других ТГ кроме $SU_2$ и $U3$, то расчет вероятности сводится к $Y\sim \mathrm{Bin}(1, [S])$ для каждого из позициооно типовых составов.

| СXС     | ПXС | XС |
|---------|-----|----|
| $[XXX]$ |     |    |
| $[XXY]$ |     |    |
| $[XYX]$ |     |    |
| $[XYY]$ |     |    |
| $[YXX]$ |     |    |
| $[YXY]$ |     |    |
| $[YYX]$ |     |    |
| $[YYY]$ |     |    |

$$\begin{cases}
  [SSS]\\
  [S_2U] \equiv \begin{cases}
    [SUS]\\
    [\overleftrightarrow{SSU}] \equiv \begin{cases}
      [SSU]\\
      [USS]\\
    \end{cases}\\
  \end{cases}\\
  [SU_2] \equiv \begin{cases}
    [USU]\\
    [\overleftrightarrow{SUU}] \equiv \begin{cases}
      [SUU]\\
      [UUS]\\
    \end{cases}\\
  \end{cases}\\
  [UUU]\\
\end{cases}$$

$\left. \right}$

- для стерео-типового состава:
  - $[SSS] = [S]^3$
  - $[SSU] = [S]^2 * [U]$
  - $[SUS] = [S]^2 * [U]$
  - $[SUU] = [S] * [U]^2$
  - $[USS] = [S]^2 * [U]$
  - $[USU] = [S] * [U]^2$
  - $[UUS] = [S] * [U]^2$
  - $[UUU] = [U]^3$

- для позиционно-типового состава:
  - $[\overleftrightarrow{SSU}] = [SSU] + [USS] = 2 * [S]^2 * [U]$
  - $[\overleftrightarrow{SUU}] = [SUU] + [UUS] = 2 * [S] * [U]^2$
  - остальные значения не отличаются от значений стерео-типового состава:
    - $[\overleftrightarrow{SSS}] = [SSS] = [S]^3$
    - $[\overleftrightarrow{SUS}] = [SUS] = [S]^2 * [U]$
    - $[\overleftrightarrow{USU}] = [USU] = [S] * [U]^2$
    - $[\overleftrightarrow{UUU}] = [UUU] = [U]^3$

- для типового состава (соответствует разложению бинома):
  - $[S_2U] = [SSU] + [USS] + [SUS] = 3 * [S]^2 * [U]$
  - $[SU_2] = [SUU] + [UUS] + [USU] = 3 * [S] * [U]^2$
  - остальные значения не отличаются от значений стерео-типового и
    позиционно-типового составов:
    - $[S_3] = [S]^3$
    - $[U_3] = [U]^3$

Уравнения расчета для стерео-видового, позиционно-видового и видового составов аналогичны уравнениям для типового состава.

Для условного $[A][B][C]$ ТАГа:

- для стерео-видового состава:
  - $[ABC] = [A] * [B] * [C]$ для любых $A$, $B$, $C$.

- для позиционно-видового состава:
  - $[\overleftrightarrow{ABC}] = [ABC] + [CBA] = 2 * [A] * [B] * [C]$
  - $[\overleftrightarrow{AAB}] = [AAB] + [BAA] = 2 * [A]^2 * [B]$
  - остальные значения не отличаются от значений стерео-видового состава:
    - $[\overleftrightarrow{ABA}] = [ABA] = [A]^2 * [B]$
    - $[\overleftrightarrow{AAA}] = [AAA] = [A]^3$

- для видового состава:
  - $[A_1B_1C_1] = [ABC] + [BCA] + [CAB] + [CBA] + [BAC] + [ACB] = 6 * [A] * [B] * [C]$
  - $[A_2B_1] = [AAB] + [ABA] + [BAA] = 3 * [A]^2 * [B]$
  - остальные значения не отличаются от значений позиционно-видового и
    стерео-видового составов:
    - $[A_3] = [AAA]$

Коэффициенты расчитываются на основании возможных перестановок для
соответствующего состава.

Общее правило для стерео-видового состава:

> Концентрация в жире ТАГа сереовидового состава равна произведению концентраций
> каждой из составляющих этот глицерид жирных кислот. [^1] (стр. 153)

== Равномерное распределение Хилдитча

Основной обнаруженный Хилдитчем факт:

> при $[S]$ < 60-65% и числе атомов углерода насыщенных кисло ($m$) >= 16-18 в
> жире содержатся лишь следы $S_3$ [^1] (стр. 153)

что много меньше статистического значения.

Обычно метод Хилдитча описывает лишь типовой состав глицеридов, не касаясь
видового.

Согласно теории равномерного распределения:

- если $[A] < ([A] + [X]) / 3$, то $A$ образует только глицериды $AX_2$
- если $[A] \approx 35\%$, то все глицериды жира принадлежат к виду $AX_2$
- если $35\% < [A] < 65\%$, то многие или почти все глицериды жира принадлежат к
  виду $A_2X$
- если $[A] \ge 70\%$, то избыток $A$ образует глицериды $A_3$ а остальные
  глицериды жира - $A_2X$

$$\begin{cases}
  0\% < [A] < 33\% & AX_2\\
  33\% < [A] < 66\% & A_2X
\end{cases}$$

где $X$ - другие жирные кислоты кроме данной кислоты $A$

== Теория Вандер Валя

Причина позиционно специфичности заключена в 1,3 статистическом, 2
статистическом механизме биосинтеза триглицеридов. И, как следствие, их 1 и 3
положения эквивалентны по всем показателям.

> Теория Вандер Валя противоречит современным представлениям о биосинтезе
> триглицеридов [^1] (стр. 167).

Для условного $[A][B][C]$ ТАГа:

* для стерео-видового состава:
** $[ABC] = [A]_{13} * [B]_2 * [C]_{13}$ для любых $A$, $B$, $C$.

* для позиционно-видового состава:
** $[\overleftrightarrow{ABC}] = [ABC] + [CBA] = 2 * [A]_{13} * [B]_2 * [C]_{13}$
** $[\overleftrightarrow{AAB}] = [AAB] + [BAA] = 2 * [A]_{13} * [A]_2 * [B]_{13}$
** остальные значения не отличаются от значений стерео-видового состава:
*** $[\overleftrightarrow{AAA}] = [AAA]$
*** $[\overleftrightarrow{ABA}] = [ABA]$

* для видового состава:
** $[ABC_1] = [ABC] + [CBA] + [BCA] + [ACB] + [CAB] + [BAC]$
** $[A_2B] = [AAB] + [BAA] + [ABA] = [A]_{13}^2 * [B]_2 + 2 *[A]_{13} * [A]_{2} * [B]_{13}$
** остальные значения не отличаются от значений позиционно-видового и стерео-видового составов:
*** $[A_3] = [AAA]`$

== Теория Ганстоуна

Описывает типовой и видовой составы исключительно растительных триглицеридов.
Это 1,3 статистическое, 2 статистическое распределение.

Позиционная специфичность распределения триглицеридов растений:

> приемущественное содержание кислот I категории в 1,3-, а кислот II категории -
> в 2-положениях (стр. 171, 179)

- I категория - большинство насыщенных кислот, ненасыщенные кислоты с $m > 18$ 
- II категория - ненасыщенные кислоты с $m \leq 18$

.Gunstone PTC
[stem]
++++
\begin{cases}
  0\% < [S] < 66\% & \begin{cases}
    [S_{3}]_G  & = & 0                                                                     &&& : & [SSS]\\
    [S_{2}U]_G & = & \left(\frac32[S]\right)^2 & = & \left(\frac32 - \frac32[U]\right)^2     & : & [SSU] + [USS] + [SUS]\\
    [SU_2]_G   & = & 3[S] - \frac92[S]^2 & = & \frac32[S](3[U] - 1)                          & : & [SUU] + [USU] + [UUS]\\
    [U_3]_G    & = & \left(1 - \frac32[S]\right)^2 & = & \left(\frac32[U] - \frac12\right)^2 & : & [UUU]\\
  \end{cases}
  \\\\
  66\% < [S] < 100\% & \begin{cases}
    [S_{3}]_G  & = & 3[S] - 2 & = & 1 - 3[U] & : & [SSS]\\
    [S_{2}U]_G & = & 3 - 3[S] & = & 3[U]     & : & [SSU] + [USS] + [SUS]\\
    [SU_2]_G   & = & 0                     &&& : & [SUU] + [USU] + [UUS]\\
    [U_3]_G    & = & 0                     &&& : & [UUU]\\
  \end{cases}\\
\end{cases}
++++

---

[stem]
++++
\begin{cases}
  S_{3_G} & = & \begin{cases}
    0\% < [S] < 66\%   & 0\\
    66\% < [S] < 100\% & 1 - [S_2U] = 1 - 3 * [U]
  \end{cases}\\
  S_{2U_G} & = & \begin{cases}
    0\% < [S] < 66\%   & (3 * [S] / 20)^2\\
    66\% < [S] < 100\% & [SSU] + [USS] + [SUS] = 3 * [U]
  \end{cases}\\
  SU_{2_G} & = & \begin{cases}
    0\% < [S] < 66\%   & 3 / 2 * [S] * (3 * [U] - 1)\\
    66\% < [S] < 100\% & 0
  \end{cases}\\
  U_{3_G} & = & \begin{cases}
    0\% < [S] < 66\% & 1 - ([SU_2] + [S_2U]) = 1 - 3 * ([S]^2 * [U] + [S] * [U]^2) = ((3 * [U] - 1) / 20)^2\\
    66\% < [S] < 100\% & 0
  \end{cases}
\end{cases}
++++

- [stem]
  ++++
  SU_2_G = \begin{cases}
    0\% < [S] < 66\% & 3 / 2 * [S] * (3 * [U] - 1)\\
    66\% < [S] < 100\% & 0
  \end{cases}
  ++++
- [stem]
  ++++
  U_3_G = \begin{cases}
    0\% < [S] < 66\% & 1 - ([SU_2] + [S_2U]) = 1 - 3 * ([S]^2 * [U] + [S] * [U]^2) = ((3 * [U] - 1) / 20)^2\\
    66\% < [S] < 100\% & 0
  \end{cases}$

После 66% отсался $S_2U$ $=>$ отсался $[SSU]$, $[USS]$ или $[SUS]$.

- для типового состава (соответствует разложению бинома):
  - $[S_2U] = [SSU] + [USS] + [SUS] = 3 * [S]^2 * [U]$
  - $[SU_2] = [SUU] + [UUS] + [USU] = 3 * [S] * [U]^2$
  - остальные значения не отличаются от значений стерео-типового и
    позиционно-типового составов:
    - $[S_3] = [S]^3$
    - $[U_3] = [U]^3$

== Calculation

> $3[A] = 2[A]_{13} + [A]_2$ [^1] (стр.116)

== Practice

> Наиболее распространенным способом проверки индивидуальных категорий состава,
> вычисленных по Вандер Валю, служит препаративная трехслойная хроматография с
> ионами $Ag+$ [^1] (стр. 170) [^88] [^319] [^464] [^837]


[^1]: Верещагин А.Г. Биохимия триглицеридов. М., Наука, 1972

[^88]: DOI [10.1007/bf02822471]
[^319]: DOI [10.1016/0009-3084(67)90021-7]
[^464]: DOI []
[^837]: DOI []

[10.1007/bf02822471]: https://sci-hub.hkvisa.net/10.1007/bf02822471
[10.1016/0009-3084(67)90021-7]: https://sci-hub.hkvisa.net/10.1016/0009-3084(67)90021-7

[10.1016/S0022-2275(20)40206-8]: https://doi.org/10.1016/S0022-2275(20)40206-8

[Верещагин А.Г. Биохимия триглицеридов. М., Наука, 1972]: # "Верещагин А.Г. Биохимия триглицеридов. М., Наука, 1972"