== ?
:eqnums: all
:05f36bf7: pass:c,q[footnote:05f36bf7-0299-5323-b01f-c08bed0759ef[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 116]]
:a411584a: pass:c,q[footnote:a411584a-6943-5623-89db-795415555d9e[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 171, с. 179]]

== Теория Ганстоуна (Gunstone)
:eqnums:

Это 1,3 статистическое, 2 статистическое распределение.

Описывает типовой и видовой составы исключительно растительных триглицеридов.

Позиционная специфичность распределения триглицеридов растений:

> преимущественное содержание кислот I категории в 1,3-, а кислот II категории - в 2-положениях {a411584a}

- I категория - большинство насыщенных кислот, ненасыщенные кислоты с $m > 18$ 
- II категория - ненасыщенные кислоты с $m \leq 18$

.Типовой состав по теории Ганстоуна
[source,math]
----
\begin{cases}\\
  0\% < [S] < 66\% & \begin{cases}\\
    [S_3]_{PCG}  & = & 0                                                                     &&& : & [SSS]\\
    [S_2U]_{PCG} & = & \left(\frac32[S]\right)^2 & = & \left(\frac32 - \frac32[U]\right)^2     & : & [SSU] + [USS] + [SUS]\\
    [SU_2]_{PCG} & = & 3[S] - \frac92[S]^2 & = & \frac32[S](3[U] - 1)                          & : & [SUU] + [USU] + [UUS]\\
    [U_3]_{PCG}  & = & \left(1 - \frac32[S]\right)^2 & = & \left(\frac32[U] - \frac12\right)^2 & : & [UUU]\\
  \end{cases}\\
  66\% < [S] < 100\% & \begin{cases}\\
    [S_3]_{PCG}  & = & 3[S] - 2 & = & 1 - 3[U] & : & [SSS]\\
    [S_2U]_{PCG} & = & 3 - 3[S] & = & 3[U]     & : & [SSU] + [USS] + [SUS]\\
    [SU_2]_{PCG} & = & 0                     &&& : & [SUU] + [USU] + [UUS]\\
    [U_3]_{PCG}  & = & 0                     &&& : & [UUU]\\
  \end{cases}\\
\end{cases}
----

.Позиционно-типовой состав по теории Ганстоуна
[source,math]
----
\begin{cases}\\
  [SSS]_{PTCG} & = & [S_3]_{PCG}\\
  [SSU]_{PTCG} & = & \frac23[S_2U]_{PCG}\\
  [SUS]_{PTCG} & = & \frac13[S_2U]_{PCG}\\
  [SUU]_{PTCG} & = & \frac23[SU_2]_{PCG}\\
  [USU]_{PTCG} & = & \frac13[SU_2]_{PCG}\\
  [UUU]_{PTCG} & = & [U_3]_{PCG}\\
\end{cases}
----

.Стерео-типовой состав по теории Ганстоуна
[source,math]
----
\begin{cases}\\
  [SSS]_{STCG} & = & [SSS]_{PTCG}        & = & [S_3]_{PCG}\\
  [SSU]_{STCG} & = & \frac12[SSU]_{PTCG} & = & \frac13[S_2U]_{PCG}\\
  [USS]_{STCG} & = & \frac12[SSU]_{PTCG} & = & \frac13[S_2U]_{PCG}\\
  [SUS]_{STCG} & = & [SUS]_{PTCG}        & = & \frac13[S_2U]_{PCG}\\
  [SUU]_{STCG} & = & \frac12[SUU]_{PTCG} & = & \frac13[SU_2]_{PCG}\\
  [UUS]_{STCG} & = & \frac12[SUU]_{PTCG} & = & \frac13[SU_2]_{PCG}\\
  [USU]_{STCG} & = & [USU]_{PTCG}        & = & \frac13[SU_2]_{PCG}\\
  [UUU]_{STCG} & = & [UUU]_{PTCG}        & = & [U_3]_{PCG}\\
\end{cases}
----

// \begin{cases}\\
//   [SSS]_{PTC} & = & [S_3]_{PC}\\
//   [SSU]_{PTC} & = & \frac23[S_2U]_{PC}\\
//   [SUS]_{PTC} & = & \frac13[S_2U]_{PC}\\
//   [SUU]_{PTC} & = & \frac23[SU_2]_{PC}\\
//   [USU]_{PTC} & = & \frac13[SU_2]_{PC}\\
//   [UUU]_{PTC} & = & [U_3]_{PC}\\
// \end{cases}

---

[source,math]
----
SU_2_G \eq \begin{cases}
  0\% < [S] < 66\% & 3 / 2 * [S] * (3 * [U] - 1)\\
  66\% < [S] < 100\% & 0
\end{cases}
----

[source,math]
----
\begin{cases}
  0\% < [S] < 66\% & 1 - ([SU_2] + [S_2U]) = 1 - 3 * ([S]^2 * [U] + [S] * [U]^2) = ((3 * [U] - 1) / 20)^2\\
  66\% < [S] < 100\% & 0
\end{cases}$
----

После 66% остался $S_2U$ $=>$ остался $[SSU]$, $[USS]$ или $[SUS]$.

- для типового состава (соответствует разложению бинома):
  - $[S_2U] = [SSU] + [USS] + [SUS] = 3 * [S]^2 * [U]$
  - $[SU_2] = [SUU] + [UUS] + [USU] = 3 * [S] * [U]^2$
  - остальные значения не отличаются от значений стерео-типового и
    позиционно-типового составов:
    - $[S_3] = [S]^3$
    - $[U_3] = [U]^3$

== Calculation

> $3[A] = 2[A]_{13} + [A]_2$ {05f36bf7}
