== ?
:2fd49011: footnote:2fd49011-2923-59ed-ac33-2d84d8a2f33f[Верещагин А. Г. Биохимия триглицеридов. – 1972.]
:0248e842: footnote:0248e842-25d5-5a0d-b508-6c22c52890f5[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 116.]
:421c31cc: footnote:421c31cc-685c-52ef-8647-94a1dda24850[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 172.]
:56d7ba11: footnote:56d7ba11-82ca-5e72-a445-ff874bb5a5fd[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 174.]
:653b0659: footnote:653b0659-c81f-50d7-a344-7220f9840ae6[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 171.]
:10_1007__BF02632456: footnote:10_1007__BF02632456[Gunstone F. D. et al. Glyceride studies. V. The distribution of unsaturated acyl groups in vegetable triglycerides //Journal of the American Oil Chemists' Society. – 1965. – Т. 42. – №. 11. – С. 965-970. https://doi.org/10.1007/BF02632456[🔗]]

== Теория Ганстоуна (Gunstone)

Это 1,3 статистическое, 2 статистическое распределение.

Описывает типовой и видовой составы исключительно растительных триглицеридов.

Позиционная специфичность распределения триглицеридов растений:

> преимущественное содержание кислот I категории в 1,3-, а кислот II категории - в 2-положениях {653b0659}

- I категория - большинство насыщенных кислот, ненасыщенные кислоты с $m > 18$ 
- II категория - ненасыщенные кислоты с $m \leq 18$

[#421c31cc]
> Теория Ганстоуна базируется на умозрительной гипотезе Савари и Денюэлля о двух позиционно-специфичных ферментах биосинтеза, согласно которой вначале в 2-положении статистически распределяются $A_{II}$, а затем 1,3-положения статистически замещаются смесью $A_I$ и остатка кислот $A_{II}$ (если он есть). {421c31cc}

---

.Типовой состав по теории Ганстоуна
[source,math]
----
\begin{array}{l}
  [S_3]_{TC/G}  &=& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & 3[S] - 2 \equiv -3[U] + 1
  \end{cases}\\
  [S_2U]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & (\frac32[S])^2 \equiv \frac32([S] - [S][U]) \equiv (\frac32 - \frac32[U])^2\\
    66\% < [S] < 100\%: & -3[S] + 3 \equiv 3[U]
  \end{cases}\\
  [SU_2]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & -\frac92[S]^2 + 3[S] \equiv \frac32[S](3[U] - 1) \equiv -\frac92[U]^2 + 6[U] - \frac32\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [U_3]_{TC/G}  &=& \begin{cases}
    0\% < [S] < 66\%:   & (1 - \frac32[S])^2 \equiv (\frac32[U] - \frac12)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}
\end{array}
----

[%collapsible]
====
[source,math]
----
\begin{array}{l}
  [S] = 1 - [U]\\
  p = \frac32[S] = \frac32 - \frac32[U]\\
  q = 1 - p = 1 - \frac32[S] = \frac32[U] - \frac12\\
  \begin{cases}
    0\% < [S] < 66\%:   & \begin{cases}
      f([U_3]) \equiv f([U'_2]) = q^2\\
      f([SU_2]) \equiv f([S'U']) = 2pq\\
      f([S_2U]) \equiv f([S'_2]) = p^2
    \end{cases}\\
    66\% < [S] < 100\%: & \begin{cases}
      f([S_2U]) \equiv f([U']) = -3[S] + 3 \equiv 3[U]\\
      f([S_3]) \equiv f([S']) = 3[S] - 2 \equiv - 3[U] + 1
    \end{cases}
  \end{cases}
\end{array}
----
====

.Видовой состав по теории Ганстоуна
[source,math]
----
\begin{array}{l}
  [^1S^2S^3S]_{SC/G} &=& 6 \frac{[^1S][^2S][^3S]}{[S]^3} [S_3]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & 6 \frac{[^1S][^2S][^3S]}{[S]^3} (3[S] - 2)
  \end{cases}\\
  [^1S^2S_2]_{SC/G}  &=& 3 \frac{[^1S][^2S]^2}{[S]^3} [S_3]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & 3 \frac{[^1S][^2S]^2}{[S]^3} (3[S] - 2)
  \end{cases}\\
  [^1S_3]_{SC/G}     &=& \frac{[^1S]^3}{[S]^3} [S_3]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & \frac{[^1S]^3}{[S]^3} (3[S] - 2)
  \end{cases}\\

  [^1S^1U^2S]_{SC/G} &=& 2 \frac{[^1S][^1U][^2S]}{[S]^2[U]} [S_2U]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac92 \frac{[^1S][^1U][^2S]}{[U]}\\
    66\% < [S] < 100\%: & 6 \frac{[^1S][^1U][^2S]}{[S]^2}
  \end{cases}\\
  [^1S^1U^1S]_{SC/G} &=& \frac{[^1S]^2[^1U]}{[S]^2[U]} [S_2U]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac94 \frac{[^1S]^2[^1U]}{[U]}\\
    66\% < [S] < 100\%: & 3 \frac{[^1S]^2[^1U]}{[S]^2}
  \end{cases}\\

  [^1S^1U^2U]_{SC/G} &=& 4 \frac{[^1U][^2U][^3U]}{[U]^3} [SU_2]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 6 \frac{[^1U][^2U][^3U]}{[U]^2} (3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [^1S^1U^1U]_{SC/G} &=& 2 \frac{[^1U][^2U]^2}{[U]^2} [SU_2]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 3 \frac{[^1U][^2U]^2}{[U]^2} (3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\

  [^1U^2U^3U]_{SC/G} &=& 6 \frac{[^1U][^2U][^3U]}{[U]^3} [U_3]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 6 \frac{[^1U][^2U][^3U]}{[U]^3} (\frac32[U] - \frac12)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [^1U^2U_2]_{SC/G}  &=& 3 \frac{[^1U][^2U]^2}{[U]^3} [U_3]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 3 \frac{[^1U][^2U]^2}{[U]^3} (\frac32[U] - \frac12)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [^1U_3]_{SC/G}     &=& \frac{[^1U]^3}{[U]^3} [U_3]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac{[^1U]^3}{[U]^3} (\frac32[U] - \frac12)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}
\end{array}
----

[%collapsible]
====
[source,math]
----
\begin{array}{l}
  P_{[^1A^2A^3A]} = [^1A^2A^3A], [^1A^3A^2A], [^2A^1A^3A], [^2A^3A^1A], [^3A^1A^2A], [^3A^2A^1A] (\times6)\\
  P_{[^1A^2A^2A]} = [^1A^2A^2A], [^2A^1A^2A], [^2A^2A^1A] (\times3)\\
  P_{[^1A^1A^1A]} = [^1A^1A^1A] (\times1)\\

  P_{[^1S^1U^2S]} = [^1S^1U^2S], [^2S^1U^1S] (\times2)\\
  P_{[^1S^1U^1S]} = [^1S^1U^1S] (\times1)\\

  P_{[^1S^1U^2U]} = [^1S^1U^2U], [^1S^2U^1U], [^1U^2U^1S], [^2U^1U^1S] (\times4)\\
  P_{[^1S^1U^1U]} = [^1S^1U^1U], [^1U^1U^1S] (\times2)\\

  n \frac{[^1S]}{[S]}\frac{[^2S]}{[S]}\frac{[^3S]}{[S]} (3[S] - 2)\\
\end{array}
----
====

> Вычисление ПТС исключается, поскольку при $[S] < 66\%$ $[S_2U]_G = [SUS]$, а $[SU_2]_G = [SUU]$. {56d7ba11}

Воспользуемся результатами расчета ТС по теории Ганстоуна, абстрагировавшись от xref:421c31cc[изначальной гипотезы] и предположив, что виды внутри типа распределяются прямо пропорционально факторам селективности {10_1007__BF02632456} их составляющих. В результате получим значения ПВС и СВС, близкие к рассчитанным по Вандер Валю.

.Позиционно-видовой состав по модифицированной теории Ганстоуна
[source,math]
----
\begin{array}{l}
  [SSS]_{PSC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & \frac{[^1S_F][^2S_F][^3S_F]}{[S]^3} (3[S] - 2)
  \end{cases}\\
  [SSU]_{PSC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac32 \frac{[^1S_F][^2S_F][^3U_F]}{[U]}\\
    66\% < [S] < 100\%: & 2 \frac{[^1S_F][^2S_F][^3U_F]}{[S]^2}
  \end{cases}\\
  [SUS]_{PSC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac34 \frac{[^1S_F][^2U_F][^3S_F]}{[U]}\\
    66\% < [S] < 100\%: & \frac{[^1S_F][^2U_F][^3S_F]}{[S]^2}
  \end{cases}\\
  [SUU]_{PSC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac{[^1S_F][^2U_F][^3U_F]}{[U]^2} (3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [USU]_{PSC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac12 \frac{[^1U_F][^2S_F][^3U_F]}{[U]^2} (3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [UUU]_{PSC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac14 \frac{[^1U_F][^2U_F][^3U_F]}{[S]^3}{[S]^3} (3[U] - 1)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}
\end{array}
----

[%collapsible]
====
[source,math]
----
\begin{array}{l}
  [^nA_F] = [^nA]_{123}F_{[^nA]_n}\\
\end{array}
----

[source,math]
----
\begin{array}{l}
  [SSS]_{PSC/G} &=& \frac{[^1S_F][^2S_F][^3S_F]}{[S]^3} [S_3]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & \frac{[^1S_F][^2S_F][^3S_F]}{[S]^3} (3[S] - 2)
  \end{cases}\\
  [SSU]_{PSC/G} &=& \frac23 \frac{[^1S_F][^2S_F][^3U_F]}{[S]^2[U]} [S_2U]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac23 \frac{[^1S_F][^2S_F][^3U_F]}{[S]^2[U]} (\frac32[S])^2\\
    66\% < [S] < 100\%: & \frac23 \frac{[^1S_F][^2S_F][^3U_F]}{[S]^2[U]} 3[U]
  \end{cases}\\
  [SUS]_{PSC/G} &=& \frac13 \frac{[^1S_F][^2U_F][^3S_F]}{[S]^2[U]} [S_2U]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac13 \frac{[^1S_F][^2U_F][^3S_F]}{[S]^2[U]} (\frac32[S])^2\\
    66\% < [S] < 100\%: & \frac13 \frac{[^1S_F][^2U_F][^3S_F]}{[S]^2[U]} 3[U]
  \end{cases}\\
  [SUU]_{PSC/G} &=& \frac23 \frac{[^1S_F][^2U_F][^3U_F]}{[S][U]^2} [SU_2]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac23 \frac{[^1S_F][^2U_F][^3U_F]}{[S][U]^2} \frac32[S](3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [USU]_{PSC/G} &=& \frac13 \frac{[^1U_F][^2S_F][^3U_F]}{[S][U]^2} [SU_2]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac13 \frac{[^1U_F][^2S_F][^3U_F]}{[S][U]^2} \frac32[S](3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [UUU]_{PSC/G} &=& \frac{[^1U_F][^2U_F][^3U_F]}{[S]^3} [U_3]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac{[^1U_F][^2U_F][^3U_F]}{[S]^3} (\frac32[U] - \frac12)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}
\end{array}
----
====

.TODO
[source,math]
----
\begin{cases}
  [S_3]_{TC/G}  &=& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & 3[S] - 2 \equiv 1 - 3[U]
  \end{cases}\\
  [S_2U]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & (\frac32[S])^2 \equiv (\frac32 - \frac32[U])^2\\
    66\% < [S] < 100\%: & 3 - 3[S] \equiv 3[U]
  \end{cases}\\
  [SU_2]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & -\frac92[S]^2 + 3[S] \equiv \frac32[S](3[U] - 1) \equiv -\frac92[U]^2 + 6[U] - \frac32\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [U_3]_{TC/G}  &=& \begin{cases}
    0\% < [S] < 66\%:   & (1 - \frac32[S])^2 \equiv (\frac32[U] - \frac12)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}
\end{cases}
----

.Позиционно-типовой состав по теории Ганстоуна
[source,math]
----
\begin{cases}
  [SSS]_{PTC/G} &=& [S_3]_{TC/G}         &=& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & 3[S] - 2
  \end{cases}\\
  [SSU]_{PTC/G} &=& \frac23[S_2U]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & (\frac23[S])^2\\
    66\% < [S] < 100\%: & 2[U]
  \end{cases}\\
  [SUS]_{PTC/G} &=& \frac13[S_2U]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & (\frac16[S])^2\\
    66\% < [S] < 100\%: & [U]
  \end{cases}\\
  [SUU]_{PTC/G} &=& \frac23[SU_2]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & [S](3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [USU]_{PTC/G} &=& \frac13[SU_2]_{TC/G} &=& \begin{cases}
    0\% < [S] < 66\%:   & \frac12[S](3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  [UUU]_{PTC/G} &=& [U_3]_{TC/G}         &=& \begin{cases}
    0\% < [S] < 66\%:   & (\frac32[U] - \frac12)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}
\end{cases}
----

.Стерео-типовой состав по теории Ганстоуна
[source,math]
----
\begin{cases}
  [SSS]_{STC/G} &=& [SSS]_{PTC/G}        &=& [S_3]_{TC/G}\\
  [SSU]_{STC/G} &=& \frac12[SSU]_{PTC/G} &=& \frac13[S_2U]_{TC/G}\\
  [USS]_{STC/G} &=& \frac12[SSU]_{PTC/G} &=& \frac13[S_2U]_{TC/G}\\
  [SUS]_{STC/G} &=& [SUS]_{PTC/G}        &=& \frac13[S_2U]_{TC/G}\\
  [SUU]_{STC/G} &=& \frac12[SUU]_{PTC/G} &=& \frac13[SU_2]_{TC/G}\\
  [UUS]_{STC/G} &=& \frac12[SUU]_{PTC/G} &=& \frac13[SU_2]_{TC/G}\\
  [USU]_{STC/G} &=& [USU]_{PTC/G}        &=& \frac13[SU_2]_{TC/G}\\
  [UUU]_{STC/G} &=& [UUU]_{PTC/G}        &=& [U_3]_{TC/G}
\end{cases}
----

---

[source,math]
----
SU_2_G \eq \begin{cases}
  0\% < [S] < 66\% & 3 / 2 * [S] * (3 * [U] - 1)\\
  66\% < [S] < 100\% & 0
\end{cases}
----

[source,math]
----
\begin{cases}
  0\% < [S] < 66\% & 1 - ([SU_2] + [S_2U]) = 1 - 3 * ([S]^2 * [U] + [S] * [U]^2) = ((3 * [U] - 1) / 20)^2\\
  66\% < [S] < 100\% & 0
\end{cases}$
----

После 66% остался $S_2U$ $=>$ остался $[SSU]$, $[USS]$ или $[SUS]$.

- для типового состава (соответствует разложению бинома):
  - $[S_2U] = [SSU] + [USS] + [SUS] = 3 * [S]^2 * [U]$
  - $[SU_2] = [SUU] + [UUS] + [USU] = 3 * [S] * [U]^2$
  - остальные значения не отличаются от значений стерео-типового и
    позиционно-типового составов:
    - $[S_3] = [S]^3$
    - $[U_3] = [U]^3$

== Calculation

> $3[A] = 2[A]_{13} + [A]_2$ {0248e842}
